import { existsSync, readdirSync, readFileSync } from 'node:fs';
import { dirname, join, relative, sep } from 'node:path';

export function postStyles(sourcePath: string): string {
  const path = join(dirname(sourcePath), 'styles.css');
  if (!existsSync(path)) return '';
  const css = readFileSync(path, 'utf8');
  if (/<\/style/i.test(css))
    throw new Error(`${path}: CSS must not contain a closing HTML style tag`);
  return `<style data-post-style>${css}</style>`;
}

export function postClientModules(sourcePath: string): string[] {
  const directory = join(dirname(sourcePath), 'scripts');
  if (!existsSync(directory)) return [];
  return readdirSync(directory, { withFileTypes: true })
    .filter((entry) => entry.isFile() && entry.name.endsWith('.post-client.ts'))
    .map((entry) => join(directory, entry.name))
    .sort();
}

export function postEnhancementModule(
  root: string,
  posts: readonly { slug: string; sourcePath: string }[],
): string {
  const entries = posts.flatMap(({ slug, sourcePath }) => {
    const modules = postClientModules(sourcePath).map((path) => {
      const module = relative(join(root, 'src/app/data'), path)
        .split(sep)
        .join('/')
        .replace(/\.ts$/, '');
      return `() => import(${JSON.stringify(module)})`;
    });
    return modules.length ? [`  [${JSON.stringify(slug)}, [${modules.join(', ')}]],`] : [];
  });
  return `// Auto-generated by scripts/build-posts.mts — do not edit manually\nimport type { PostEnhancementLoader } from '../models/post-enhancement.model';\n\nexport const POST_ENHANCEMENTS = new Map<string, PostEnhancementLoader[]>([\n${entries.join('\n')}\n]);\n`;
}
