import { mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { load as loadYaml } from 'js-yaml';
import { JSDOM } from 'jsdom';
import { createHighlighter } from 'shiki';
import type { CvData } from '../src/app/models/cv.model';
import type { Post } from '../src/app/models/post.model';
import type { SearchDocument, SerializedSearchIndex } from '../src/app/models/search.model';
import { comparePostsByPublication } from '../src/app/utils/blog-pagination';
import { createSearchIndex } from '../src/app/utils/search-index';
import { type AgentPost, buildAgentFiles, writeAgentFiles } from './lib/agent-content.mts';
import { renderCvMarkdown } from './lib/cv-markdown.mts';
import { parsePostSource } from './lib/front-matter.mts';
import { normalizePostImageHref, renderMdx } from './lib/mdx-renderer.mts';
import { buildPersonData } from './lib/person-data.mts';
import { buildPostExcerpt } from './lib/post-excerpt.mts';
import { discoverPostSources } from './lib/post-sources.mts';
import { loadSiteConfiguration } from './lib/site-config.mts';
import { buildSyndicationFeeds } from './lib/syndication.mts';

const ROOT = fileURLToPath(new URL('..', import.meta.url));
const POSTS_DIR = join(ROOT, 'content/posts');
const DATA_DIR = join(ROOT, 'src/app/data');
const CONTENT_DIR = join(DATA_DIR, 'posts');
const GENERATED = '// Auto-generated by scripts/build-posts.mts — do not edit manually\n';

function searchableText(html: string): string {
  const { document } = new JSDOM(html).window;
  for (const node of document.querySelectorAll(
    'svg, script, style, .heading-permalink, .code-header',
  )) {
    node.remove();
  }
  const walker = document.createTreeWalker(document.body, 4);
  const parts: string[] = [];
  while (walker.nextNode()) parts.push(walker.currentNode.textContent ?? '');
  return parts.join(' ').replace(/\s+/g, ' ').trim();
}

async function writePosts(posts: Post[]): Promise<void> {
  rmSync(CONTENT_DIR, { recursive: true, force: true });
  mkdirSync(CONTENT_DIR, { recursive: true });
  const summaries = posts.map(({ contentHtml: _html, toc: _toc, ...summary }) => summary);
  writeFileSync(
    join(DATA_DIR, 'posts.ts'),
    `${GENERATED}import type { PostSummary } from '../models/post.model';\n\nexport const POSTS: PostSummary[] = ${JSON.stringify(summaries, null, 2)};\n`,
  );

  for (const { slug, contentHtml, toc } of posts) {
    const filename = join(CONTENT_DIR, `${slug}.ts`);
    mkdirSync(dirname(filename), { recursive: true });
    const modelPath = `${'../'.repeat(slug.split('/').length + 1)}models/post.model`;
    writeFileSync(
      filename,
      `${GENERATED}import type { PostContent } from '${modelPath}';\n\nexport const POST_CONTENT: PostContent = ${JSON.stringify({ contentHtml, toc }, null, 2)};\n`,
    );
  }
  const loaders = posts
    .map(
      ({ slug }) =>
        `  [${JSON.stringify(slug)}, () => import(${JSON.stringify(`./posts/${slug}`)}).then(m => m.POST_CONTENT)],`,
    )
    .join('\n');
  writeFileSync(
    join(DATA_DIR, 'post-loaders.ts'),
    `${GENERATED}import type { PostContent } from '../models/post.model';\n\nexport const POST_LOADERS = new Map<string, () => Promise<PostContent>>([\n${loaders}\n]);\n`,
  );

  const documents: SearchDocument[] = posts.map((post, id) => ({
    id,
    slug: post.slug,
    title: post.title,
    date: post.date,
    description: post.description ?? '',
    content: searchableText(post.contentHtml),
  }));
  const index = createSearchIndex();
  for (const document of documents) index.add(document);
  const serialized: SerializedSearchIndex = [];
  await index.export(async (key, data) => {
    serialized.push([key, data]);
  });
  writeFileSync(
    join(DATA_DIR, 'search-index.ts'),
    `${GENERATED}import type { SearchDocument, SerializedSearchIndex } from '../models/search.model';\n\nexport const SEARCH_DOCUMENTS: SearchDocument[] = ${JSON.stringify(documents, null, 2)};\n\nexport const SEARCH_INDEX: SerializedSearchIndex = ${JSON.stringify(serialized)};\n`,
  );
  console.log(`Generated ${posts.length} post summaries, individual bodies, and a search index`);
}

async function main(): Promise<void> {
  const configuration = loadSiteConfiguration(join(ROOT, 'configs'));
  mkdirSync(DATA_DIR, { recursive: true });
  for (const [filename, type, name, value] of [
    ['site-config', 'SiteConfig', 'SITE_CONFIG', configuration.site],
    ['blog-config', 'BlogConfig', 'BLOG_CONFIG', configuration.blog],
    ['comments-config', 'CommentsConfig', 'COMMENTS_CONFIG', configuration.comments],
  ] as const) {
    writeFileSync(
      join(DATA_DIR, `${filename}.ts`),
      `${GENERATED}import type { ${type} } from '../models/config.model';\n\nexport const ${name}: ${type} = ${JSON.stringify(value, null, 2)};\n`,
    );
  }
  const rawPosts = discoverPostSources(POSTS_DIR)
    .map(({ slug, sourcePath }) => {
      const relativeSource = `content/posts/${slug}/index.mdx`;
      const { metadata, body } = parsePostSource(readFileSync(sourcePath, 'utf-8'), relativeSource);
      return { slug, sourcePath, meta: metadata, mdx: body };
    })
    .filter(({ meta }) => !meta.draft);

  const languages = [
    ...new Set(
      rawPosts.flatMap(({ mdx }) => [...mdx.matchAll(/```(\w+)/g)].map((match) => match[1])),
    ),
  ];
  const highlighter = await createHighlighter({
    themes: ['catppuccin-latte', 'catppuccin-mocha'],
    langs: languages.length ? languages : ['text'],
  });
  const agentPosts: AgentPost[] = [];
  try {
    const posts: Post[] = await Promise.all(
      rawPosts.map(async ({ slug, meta, mdx, sourcePath }) => {
        const { draft: _draft, ...summary } = meta;
        if (summary.coverImage)
          summary.coverImage = normalizePostImageHref(summary.coverImage, slug);
        const rendered = await renderMdx(mdx, slug, sourcePath, highlighter);
        agentPosts.push({ ...summary, slug, markdownHtml: rendered.markdownHtml });
        return {
          ...summary,
          slug,
          excerptHtml: buildPostExcerpt(rendered.markdownHtml),
          contentHtml: rendered.html,
          toc: rendered.toc,
        };
      }),
    );
    posts.sort(comparePostsByPublication);
    await writePosts(posts);
  } finally {
    highlighter.dispose();
  }

  const redirects = configuration.redirects;
  writeFileSync(
    join(DATA_DIR, 'redirects.ts'),
    `${GENERATED}import type { Redirect } from '../models/redirect.model';\n\nexport const REDIRECTS: Redirect[] = ${JSON.stringify(redirects, null, 2)};\n`,
  );
  const cv = renderCvMarkdown(
    loadYaml(readFileSync(join(ROOT, 'content/cv.yaml'), 'utf-8')) as CvData,
  );
  writeFileSync(
    join(DATA_DIR, 'cv.ts'),
    `${GENERATED}import type { CvData } from '../models/cv.model';\n\nexport const CV_DATA: CvData = ${JSON.stringify(cv, null, 2)};\n`,
  );
  console.log('Generated redirects and CV data');
  writeFileSync(
    join(DATA_DIR, 'person.ts'),
    `${GENERATED}import type { PersonStructuredData } from '../models/structured-data.model';\n\nexport const PERSON_DATA: PersonStructuredData = ${JSON.stringify(buildPersonData(cv, configuration.site), null, 2)};\n`,
  );
  const agentFiles = buildAgentFiles(agentPosts, cv, configuration.site);
  for (const [path, content] of buildSyndicationFeeds(agentPosts, configuration.site)) {
    agentFiles.set(path, content);
  }
  writeAgentFiles(join(ROOT, '.generated/agent-content'), agentFiles);
  console.log(`Generated ${agentFiles.size} Markdown, index, and feed files`);
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) await main();
