import { existsSync, readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { JSDOM } from 'jsdom';
import { createHighlighter } from 'shiki';
import type { Post } from '../src/app/models/post.model';
import type { SearchDocument, SerializedSearchIndex } from '../src/app/models/search.model';
import { comparePostsByPublication } from '../src/app/utils/blog-pagination';
import { createSearchIndex } from '../src/app/utils/search-index';
import { type AgentPost, buildAgentFiles, renderArticleMarkdown } from './lib/agent-content.mts';
import {
  type CachedPost,
  digest,
  encodeCachedPost,
  generatedDigest,
  InputDigests,
  outputDigest,
  readCachedPost,
  treeFiles,
} from './lib/content-cache.mts';
import { renderCvMarkdown } from './lib/cv-markdown.mts';
import { parseCvSource } from './lib/cv-source.mts';
import { parsePostSource } from './lib/front-matter.mts';
import { publishGeneratedFiles } from './lib/generated-files.mts';
import { normalizePostImageHref, renderMdx } from './lib/mdx-renderer.mts';
import { buildPersonData } from './lib/person-data.mts';
import { postEnhancementModule } from './lib/post-assets.mts';
import { buildPostExcerpt } from './lib/post-excerpt.mts';
import { discoverPostSources } from './lib/post-sources.mts';
import { loadSiteConfiguration } from './lib/site-config.mts';
import { buildSyndicationFeeds } from './lib/syndication.mts';

const ROOT = fileURLToPath(new URL('..', import.meta.url));
const GENERATED = '// Auto-generated by scripts/build-posts.mts — do not edit manually\n';

function searchableText(html: string): string {
  const dom = new JSDOM(html);
  try {
    const { document } = dom.window;
    for (const node of document.querySelectorAll(
      'svg, script, style, .heading-permalink, .code-header',
    ))
      node.remove();
    const walker = document.createTreeWalker(document.body, 4);
    const parts: string[] = [];
    while (walker.nextNode()) parts.push(walker.currentNode.textContent ?? '');
    return parts.join(' ').replace(/\s+/g, ' ').trim();
  } finally {
    dom.window.close();
  }
}

async function buildPostModules(
  posts: Post[],
  searchTexts: Map<string, string>,
): Promise<Map<string, string>> {
  const files = new Map<string, string>();
  const summaries = posts.map(({ contentHtml: _html, toc: _toc, ...summary }) => summary);
  files.set(
    'posts.ts',
    `${GENERATED}import type { PostSummary } from '../models/post.model';\n\nexport const POSTS: PostSummary[] = ${JSON.stringify(summaries, null, 2)};\n`,
  );
  for (const { slug, contentHtml, toc } of posts) {
    const modelPath = `${'../'.repeat(slug.split('/').length + 1)}models/post.model`;
    files.set(
      `posts/${slug}.ts`,
      `${GENERATED}import type { PostContent } from '${modelPath}';\n\nexport const POST_CONTENT: PostContent = ${JSON.stringify({ contentHtml, toc }, null, 2)};\n`,
    );
  }
  const loaders = posts
    .map(
      ({ slug }) =>
        `  [${JSON.stringify(slug)}, () => import(${JSON.stringify(`./posts/${slug}`)}).then(m => m.POST_CONTENT)],`,
    )
    .join('\n');
  files.set(
    'post-loaders.ts',
    `${GENERATED}import type { PostContent } from '../models/post.model';\n\nexport const POST_LOADERS = new Map<string, () => Promise<PostContent>>([\n${loaders}\n]);\n`,
  );
  const documents: SearchDocument[] = posts.map((post, id) => ({
    id,
    slug: post.slug,
    title: post.title,
    date: post.date,
    description: post.description ?? '',
    content: searchTexts.get(post.slug)!,
  }));
  const index = createSearchIndex();
  for (const document of documents) index.add(document);
  const serialized: SerializedSearchIndex = [];
  await index.export(async (key, data) => {
    serialized.push([key, data]);
  });
  files.set(
    'search-index.ts',
    `${GENERATED}import type { SearchDocument, SerializedSearchIndex } from '../models/search.model';\n\nexport const SEARCH_DOCUMENTS: SearchDocument[] = ${JSON.stringify(documents, null, 2)};\n\nexport const SEARCH_INDEX: SerializedSearchIndex = ${JSON.stringify(serialized)};\n`,
  );
  return files;
}

/** Build every representation before publishing any derived files. */
export async function generateData(
  root = ROOT,
): Promise<{ rendered: number; cached: number; changed: number; removed: number }> {
  const inputs = new InputDigests();
  const compiler = inputs.files(
    [
      ...treeFiles(join(ROOT, 'scripts')).filter(
        (path) => !path.includes('/fixtures/') && !path.endsWith('.spec.mts'),
      ),
      ...['package.json', 'pnpm-lock.yaml', 'tsconfig.json', 'tsconfig.scripts.json'].map((path) =>
        join(ROOT, path),
      ),
    ],
    true,
  );
  const sources = discoverPostSources(join(root, 'content/posts'));
  const keys = new Map(
    sources.map(({ slug, sourcePath }) => [
      slug,
      inputs.files(treeFiles(dirname(sourcePath)), true),
    ]),
  );
  const fingerprint = digest(
    JSON.stringify([
      compiler,
      [...keys],
      inputs.files([...treeFiles(join(root, 'configs')), join(root, 'content/cv.yaml')]),
    ]),
  );
  const cacheDirectory = join(root, '.generated/content-cache');
  const outputDirectories = [join(root, 'src/app/data'), join(root, '.generated/agent-content')];
  try {
    const manifest = JSON.parse(readFileSync(join(cacheDirectory, 'manifest.json'), 'utf8'));
    if (
      manifest.fingerprint === fingerprint &&
      outputDirectories.every(existsSync) &&
      manifest.outputs === outputDigest(outputDirectories)
    ) {
      console.log('Content is unchanged; reused all generated files');
      return { rendered: 0, cached: manifest.count, changed: 0, removed: 0 };
    }
  } catch {
    /* A missing or invalid cache is a normal cold build. */
  }
  const configuration = loadSiteConfiguration(join(root, 'configs'));
  const rawPosts = sources
    .map(({ slug, sourcePath }) => {
      const { metadata, body } = parsePostSource(
        readFileSync(sourcePath, 'utf8'),
        `content/posts/${slug}/index.mdx`,
      );
      return { slug, sourcePath, meta: metadata, mdx: body };
    })
    .filter(({ meta }) => !meta.draft);
  const cacheFiles = new Map<string, string>();
  const cachedPosts = new Map<string, CachedPost>();
  const cacheKeys = new Map(
    rawPosts.map(({ slug }) => [
      slug,
      digest(JSON.stringify([compiler, keys.get(slug), configuration.site])),
    ]),
  );
  for (const { slug } of rawPosts) {
    const cached = readCachedPost(join(cacheDirectory, `${slug}.json`), cacheKeys.get(slug)!);
    if (cached) cachedPosts.set(slug, cached);
  }
  const languages = [
    ...new Set(
      rawPosts
        .filter(({ slug }) => !cachedPosts.has(slug))
        .flatMap(({ mdx }) => [...mdx.matchAll(/```(\w+)/g)].map((match) => match[1])),
    ),
  ];
  const highlighter =
    cachedPosts.size === rawPosts.length
      ? undefined
      : await createHighlighter({
          themes: ['catppuccin-latte', 'catppuccin-mocha'],
          langs: languages.length ? languages : ['text'],
        });
  const agentPosts: AgentPost[] = [];
  const searchTexts = new Map<string, string>();
  let posts: Post[];
  try {
    posts = await Promise.all(
      rawPosts.map(async ({ slug, meta, mdx, sourcePath }) => {
        const remember = (value: CachedPost) => {
          agentPosts.push(value.agent);
          searchTexts.set(slug, value.searchText);
          cacheFiles.set(`${slug}.json`, encodeCachedPost(cacheKeys.get(slug)!, value));
          return value.post;
        };
        const cached = cachedPosts.get(slug);
        if (cached) return remember(cached);
        const { draft: _draft, ...summary } = meta;
        if (summary.coverImage)
          summary.coverImage = normalizePostImageHref(summary.coverImage, slug);
        const rendered = await renderMdx(mdx, slug, sourcePath, highlighter!);
        const agent = { ...summary, slug, markdownHtml: rendered.markdownHtml };
        const post = {
          ...summary,
          slug,
          excerptHtml: buildPostExcerpt(rendered.markdownHtml),
          contentHtml: rendered.html,
          toc: rendered.toc,
        };
        return remember({
          post,
          agent: { ...agent, markdownExport: renderArticleMarkdown(agent, configuration.site) },
          searchText: searchableText(post.contentHtml),
        });
      }),
    );
  } finally {
    highlighter?.dispose();
  }
  posts.sort(comparePostsByPublication);
  const dataFiles = await buildPostModules(posts, searchTexts);
  dataFiles.set('post-enhancements.ts', postEnhancementModule(root, rawPosts));
  for (const [filename, type, name, value] of [
    ['site-config', 'SiteConfig', 'SITE_CONFIG', configuration.site],
    ['blog-config', 'BlogConfig', 'BLOG_CONFIG', configuration.blog],
    ['comments-config', 'CommentsConfig', 'COMMENTS_CONFIG', configuration.comments],
  ] as const) {
    dataFiles.set(
      `${filename}.ts`,
      `${GENERATED}import type { ${type} } from '../models/config.model';\n\nexport const ${name}: ${type} = ${JSON.stringify(value, null, 2)};\n`,
    );
  }
  dataFiles.set(
    'redirects.ts',
    `${GENERATED}import type { Redirect } from '../models/redirect.model';\n\nexport const REDIRECTS: Redirect[] = ${JSON.stringify(configuration.redirects, null, 2)};\n`,
  );
  const cv = renderCvMarkdown(parseCvSource(readFileSync(join(root, 'content/cv.yaml'), 'utf8')));
  dataFiles.set(
    'cv.ts',
    `${GENERATED}import type { CvData } from '../models/cv.model';\n\nexport const CV_DATA: CvData = ${JSON.stringify(cv, null, 2)};\n`,
  );
  dataFiles.set(
    'person.ts',
    `${GENERATED}import type { PersonStructuredData } from '../models/structured-data.model';\n\nexport const PERSON_DATA: PersonStructuredData = ${JSON.stringify(buildPersonData(cv, configuration.site), null, 2)};\n`,
  );
  const agentFiles = buildAgentFiles(agentPosts, cv, configuration.site);
  for (const [path, content] of buildSyndicationFeeds(agentPosts, configuration.site))
    agentFiles.set(path, content);
  const trees = [
    { directory: join(root, 'src/app/data'), files: dataFiles },
    { directory: join(root, '.generated/agent-content'), files: agentFiles },
  ];
  cacheFiles.set(
    'manifest.json',
    JSON.stringify({ fingerprint, outputs: generatedDigest(trees), count: posts.length }),
  );
  const result = publishGeneratedFiles([
    ...trees,
    { directory: cacheDirectory, files: cacheFiles },
  ]);
  const stats = { rendered: posts.length - cachedPosts.size, cached: cachedPosts.size, ...result };
  console.log(
    `Generated ${posts.length} posts (${stats.rendered} rendered, ${stats.cached} cached) and ${agentFiles.size} exports; wrote ${result.changed}, removed ${result.removed} files (including cache)`,
  );
  return stats;
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href)
  await generateData();
