import { readdirSync, readFileSync, writeFileSync } from 'fs';
import { join, basename } from 'path';
import { marked } from 'marked';
import { createHighlighter } from 'shiki';
import { mathBlock, mathInline } from './lib/math-extensions.mjs';
import { createCodeRenderer } from './lib/code-renderer.mjs';
import { tableRenderer } from './lib/table-renderer.mjs';

const ROOT = new URL('..', import.meta.url).pathname;
const CONFIG_DIR = join(ROOT, 'content/config');
const POSTS_DIR = join(ROOT, 'content/posts');
const OUTPUT = join(ROOT, 'src/app/data/posts.ts');

// Collect languages used across all posts for Shiki
function collectLangs(posts) {
  const langs = new Set();
  for (const md of posts) {
    for (const match of md.matchAll(/```(\w+)/g)) {
      langs.add(match[1]);
    }
  }
  return [...langs];
}

async function main() {
  const configFiles = readdirSync(CONFIG_DIR)
    .filter(f => f.endsWith('.json'))
    .sort();

  const rawPosts = configFiles.map(file => {
    const slug = basename(file, '.json');
    const meta = JSON.parse(readFileSync(join(CONFIG_DIR, file), 'utf-8'));
    const md = readFileSync(join(POSTS_DIR, `${slug}.md`), 'utf-8');
    return { slug, meta, md };
  });

  // Create Shiki highlighter with all needed languages
  const langs = collectLangs(rawPosts.map(p => p.md));
  const highlighter = await createHighlighter({
    themes: ['github-light', 'github-dark'],
    langs: langs.length ? langs : ['text'],
  });

  // Configure marked with math extensions + Shiki code renderer + table renderer
  marked.use({
    extensions: [mathBlock, mathInline],
    renderer: {
      code: createCodeRenderer(highlighter),
      table: tableRenderer,
    },
  });

  const posts = rawPosts.map(({ slug, meta, md }) => {
    const contentHtml = marked.parse(md, { async: false });
    return { slug, ...meta, contentHtml };
  });

  posts.sort((a, b) => b.date.localeCompare(a.date));

  const output = `// Auto-generated by scripts/build-posts.mjs — do not edit manually
import { Post } from '../models/post.model';

export const POSTS: Post[] = ${JSON.stringify(posts, null, 2)};
`;

  writeFileSync(OUTPUT, output, 'utf-8');
  console.log(`Generated ${posts.length} posts → src/app/data/posts.ts`);
}

main();
