import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'fs';
import yaml from 'js-yaml';
import { Marked } from 'marked';
import { basename, join } from 'path';
import { createHighlighter } from 'shiki';
import { createCodeRenderer } from './lib/code-renderer.mjs';
import { mathBlock, mathInline } from './lib/math-extensions.mjs';
import { tableRenderer } from './lib/table-renderer.mjs';

const ROOT = new URL('..', import.meta.url).pathname;
const CONFIG_DIR = join(ROOT, 'content/config');
const POSTS_DIR = join(ROOT, 'content/posts');
const DATA_DIR = join(ROOT, 'src/app/data');
const OUTPUT = join(DATA_DIR, 'posts.ts');
const REDIRECTS_INPUT = join(ROOT, 'content/redirects.yaml');
const REDIRECTS_OUTPUT = join(DATA_DIR, 'redirects.ts');
const CV_INPUT = join(ROOT, 'content/cv.yaml');
const CV_OUTPUT = join(DATA_DIR, 'cv.ts');
const POST_ASSET_BASE = '/posts';

// Collect languages used across all posts for Shiki
function collectLangs(posts) {
  const langs = new Set();
  for (const md of posts) {
    for (const match of md.matchAll(/```(\w+)/g)) {
      langs.add(match[1]);
    }
  }
  return [...langs];
}

function isRootedOrRemoteHref(href) {
  return /^(?:[a-z][a-z\d+.-]*:|\/\/|#|\/)/i.test(href);
}

function normalizePostImageHref(href, slug) {
  if (isRootedOrRemoteHref(href)) {
    return href;
  }

  const localHref = href.replace(/^\.\//, '');
  if (localHref.startsWith(`${slug}/`)) {
    return `${POST_ASSET_BASE}/${localHref}`;
  }

  return `${POST_ASSET_BASE}/${slug}/${localHref}`;
}

function renderMarkdown(md, slug, highlighter) {
  // Custom image renderer: publishes post-local assets from content/posts/<slug>.
  const imageRenderer = (token) => {
    const src = normalizePostImageHref(token.href, slug);
    const alt = token.text || '';
    const title = token.title ? ` title="${token.title}"` : '';
    return `<img src="${src}" alt="${alt}"${title} loading="lazy" decoding="async">`;
  };

  const renderer = new Marked({
    extensions: [mathBlock, mathInline],
    renderer: {
      code: createCodeRenderer(highlighter),
      table: tableRenderer,
      image: imageRenderer,
    },
  });

  return renderer.parse(md, { async: false });
}

async function main() {
  mkdirSync(DATA_DIR, { recursive: true });

  const configFiles = readdirSync(CONFIG_DIR)
    .filter((f) => f.endsWith('.json'))
    .sort();

  const rawPosts = configFiles.map((file) => {
    const slug = basename(file, '.json');
    const meta = JSON.parse(readFileSync(join(CONFIG_DIR, file), 'utf-8'));
    const md = readFileSync(join(POSTS_DIR, `${slug}.md`), 'utf-8');
    return { slug, meta, md };
  });

  // Create Shiki highlighter with all needed languages
  const langs = collectLangs(rawPosts.map((p) => p.md));
  const highlighter = await createHighlighter({
    themes: ['catppuccin-latte', 'catppuccin-mocha'],
    langs: langs.length ? langs : ['text'],
  });

  const posts = rawPosts.map(({ slug, meta, md }) => {
    const contentHtml = renderMarkdown(md, slug, highlighter);
    return { slug, ...meta, contentHtml };
  });

  posts.sort((a, b) => b.date.localeCompare(a.date));

  const output = `// Auto-generated by scripts/build-posts.mjs — do not edit manually
import { Post } from '../models/post.model';

export const POSTS: Post[] = ${JSON.stringify(posts, null, 2)};
`;

  writeFileSync(OUTPUT, output, 'utf-8');
  console.log(`Generated ${posts.length} posts → src/app/data/posts.ts`);

  // Build redirects
  let redirects = [];
  if (existsSync(REDIRECTS_INPUT)) {
    redirects = yaml.load(readFileSync(REDIRECTS_INPUT, 'utf-8')) || [];
  }

  const redirectsOutput = `// Auto-generated by scripts/build-posts.mjs — do not edit manually
import { Redirect } from '../models/redirect.model';

export const REDIRECTS: Redirect[] = ${JSON.stringify(redirects, null, 2)};
`;

  writeFileSync(REDIRECTS_OUTPUT, redirectsOutput, 'utf-8');
  console.log(`Generated ${redirects.length} redirects → src/app/data/redirects.ts`);

  // Build CV data
  let cv = {};
  if (existsSync(CV_INPUT)) {
    cv = yaml.load(readFileSync(CV_INPUT, 'utf-8')) || {};
  }

  const cvOutput = `// Auto-generated by scripts/build-posts.mjs — do not edit manually
import { CvData } from '../models/cv.model';

export const CV_DATA: CvData = ${JSON.stringify(cv, null, 2)};
`;

  writeFileSync(CV_OUTPUT, cvOutput, 'utf-8');
  console.log(`Generated CV data → src/app/data/cv.ts`);
}

main();
