import { readdirSync, readFileSync, writeFileSync } from 'fs';
import { join, basename } from 'path';
import { marked } from 'marked';

const ROOT = new URL('..', import.meta.url).pathname;
const CONFIG_DIR = join(ROOT, 'content/config');
const POSTS_DIR = join(ROOT, 'content/posts');
const OUTPUT = join(ROOT, 'src/app/data/posts.ts');

function escapeHtml(s) {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

// marked extension: protect math delimiters and convert to \(...\) / \[...\]
const mathBlock = {
  name: 'mathBlock',
  level: 'block',
  start(src) { return src.match(/\$\$/)?.index; },
  tokenizer(src) {
    const match = src.match(/^\$\$([\s\S]+?)\$\$/);
    if (match) {
      return { type: 'mathBlock', raw: match[0], text: match[1].trim() };
    }
  },
  renderer(token) {
    return `<div class="math-display">\\[${escapeHtml(token.text)}\\]</div>\n`;
  },
};

const mathInline = {
  name: 'mathInline',
  level: 'inline',
  start(src) { return src.match(/\$/)?.index; },
  tokenizer(src) {
    const match = src.match(/^\$([^\$\n]+?)\$/);
    if (match) {
      return { type: 'mathInline', raw: match[0], text: match[1] };
    }
  },
  renderer(token) {
    return `\\(${escapeHtml(token.text)}\\)`;
  },
};

marked.use({ extensions: [mathBlock, mathInline] });

const configFiles = readdirSync(CONFIG_DIR)
  .filter(f => f.endsWith('.json'))
  .sort();

const posts = configFiles.map(file => {
  const slug = basename(file, '.json');
  const meta = JSON.parse(readFileSync(join(CONFIG_DIR, file), 'utf-8'));
  const md = readFileSync(join(POSTS_DIR, `${slug}.md`), 'utf-8');
  const contentHtml = marked.parse(md, { async: false });

  return { slug, ...meta, contentHtml };
});

posts.sort((a, b) => b.date.localeCompare(a.date));

const output = `// Auto-generated by scripts/build-posts.mjs — do not edit manually
import { Post } from '../models/post.model';

export const POSTS: Post[] = ${JSON.stringify(posts, null, 2)};
`;

writeFileSync(OUTPUT, output, 'utf-8');
console.log(`Generated ${posts.length} posts → src/app/data/posts.ts`);
